apiVersion: v1
kind: Service
metadata:
  name: distilgpt2-demo-service
  labels:
    app: distilgpt2-demo-vllm
spec:
  selector:
    app: distilgpt2-demo-vllm
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP