apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: distilgpt2-apps
  namespace: flux-system
spec:
  interval: 1m
  path: "./flux-config/clusters/dev/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system